const locations = [
  "Mirpur 1",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Mirpur 12",
  "Mirpur 14",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Dhanmondi",
  "Gulshan 1",
  "Gulshan 2",
  "Gulshan",
  "Banani",
  "Uttara",
  "Uttara North",
  "Uttara South",
  "Farmgate",
  "Motijheel",
  "Sadarghat",
  "Gulistan",
  "Mohakhali",
  "Bashundhara",
  "Badda",
  "Rampura",
  "Malibagh",
  "Shantinagar",
  "Paltan",
  "Shahbag",
  "Elephant Road",
  "New Market",
  "Azimpur",
  "Lalbagh",
  "Old Dhaka",
  "Wari",
  "Demra",
  "Jatrabari",
  "Postogola",
  "Khilgaon",
  "Basabo",
  "Mugda",
  "Matuail",
  "Narayanganj",
  "Tejgaon",
  "Moghbazar",
  "Mouchak",
  "Hatirjheel",
  "Niketan",
  "Baridhara",
  "Khilkhet",
  "Airport",
  "Diabari",
  "Tongi",
  "Gazipur",
];

export default locations;